<?php

/**
 * @file
 * Functions to support theming in the mrjer theme.
 */

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function citysite_preprocess_html(&$variables) {

}

/**
* Twig templating on content type
 */
function citysite_theme_suggestions_page_alter(array &$suggestions, array $variables) {
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $content_type = $node->bundle();
        $suggestions[] = 'page__'.$content_type;
    }
}